version: "3"
services: 
    php-fpm70:
        image: navioo/php-fpm7.0:1.0
        restart: always
        container_name: php-fpm7.0
        tty: true
        ports: 
            - "9000:9000"
        volumes: 
            - /ws/www:/web
            - /ws/volumes/php-fpm7.0/conf/php.ini:/etc/php.ini
            - /ws/volumes/php-fpm7.0/conf/php-fpm.conf:/etc/php-fpm.conf
            - /ws/volumes/php-fpm7.0/conf/php-fpm.d:/etc/php-fpm.d
            - /ws/volumes/php-fpm7.0/log/php-fpm.log:/var/log/php-fpm.log
        environment: 
            - TZ=Asia/Shanghai

