version: "3"
services:
    mysql57:
        image: navioo/mysql5.7:1.0
        restart: always
        container_name: mysql5.7
        tty: true
        ports:
            - "3306:3306"
        volumes: 
            - /ws/volumes/mysql5.7/conf.d:/etc/mysql/conf.d
            - /ws/volumes/mysql5.7/data:/var/lib/mysql
            - /ws/volumes/mysql5.7/log:/var/log/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - TZ=Asia/Shanghai