version: "3"
services: 
    nginx:
        image: navioo/nginx:1.16.1
        restart: always
        container_name: nginx1.16.1
        tty: true
        ports: 
            - "80:80"
            - "443:443"
        volumes: 
            - /ws/www:/web
            - /ws/env:/env
            - /ws/volumes/nginx1.16.1/conf/nginx.conf:/etc/nginx/nginx.conf
            - /ws/volumes/nginx1.16.1/conf/conf.d:/etc/nginx/conf.d
            - /ws/volumes/nginx1.16.1/log:/var/log/nginx
        environment: 
            - TZ=Asia/Shanghai
        depends_on:
          - php-fpm72
        links:
          - php-fpm72:php-fpm72
    php-fpm72:
        image: navioo/php-fpm:7.2.27
        restart: always
        container_name: php-fpm7.2.27
        tty: true
        ports: 
            - "9000:9000"
        volumes: 
            - /ws/www:/web
            - /ws/volumes/php-fpm7.2.27/conf/php.ini:/etc/php.ini
            - /ws/volumes/php-fpm7.2.27/conf/php-fpm.conf:/etc/php-fpm.conf
            - /ws/volumes/php-fpm7.2.27/conf/php-fpm.d:/etc/php-fpm.d
            - /ws/volumes/php-fpm7.2.27/log/error.log:/var/log/php-fpm/error.log
        environment:
            - TZ=Asia/Shanghai