version: "3"
services: 
    php-fpm72:
        image: navioo/php-fpm:7.2.27
        restart: always
        container_name: php-fpm7.2.27
        tty: true
        ports: 
            - "9000:9000"
<<<<<<< HEAD
#            - "9001:9001"
#            - "9002:9002"
#            - "5601:5601"
=======
>>>>>>> bb885c07d9948cab7df0234804715125b7eef718
        volumes: 
            - /ws/www:/web
            - /ws/volumes/php-fpm7.2.27/conf/php.ini:/etc/php.ini
            - /ws/volumes/php-fpm7.2.27/conf/php-fpm.conf:/etc/php-fpm.conf
            - /ws/volumes/php-fpm7.2.27/conf/php-fpm.d:/etc/php-fpm.d
            - /ws/volumes/php-fpm7.2.27/log/error.log:/var/log/php-fpm/error.log
        environment: 
            - TZ=Asia/Shanghai
<<<<<<< HEAD
#        networks:
#            - env_dnmp_default
#networks:
#        env_dnmp_default:
#            external: true
=======

>>>>>>> bb885c07d9948cab7df0234804715125b7eef718
